### ISSUE TITLE
about the pretrain when training

### ISSUE THREAD

**Issue by yihaoyao402** [adelacvg/NS2VC#25]
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /charactr/vocos-mel-24khz/resolve/main/config.yaml (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B8B793E310>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/charactr/vocos-mel-24khz/resolve/main/config.yaml
Traceback (most recent call last):
  File "E:\pythoncode\NS2VC-vc-v2\train.py", line 3, in <module>
    trainer = Trainer()
  File "E:\pythoncode\NS2VC-vc-v2\model.py", line 809, in __init__
    self.vocos = Vocos.from_pretrained("charactr/vocos-mel-24khz")
  File "D:\anaconda\envs\pytorch\lib\site-packages\vocos\pretrained.py", line 65, in from_pretrained
    config_path = hf_hub_download(repo_id=repo_id, filename="config.yaml")
  File "D:\anaconda\envs\pytorch\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\anaconda\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py", line 1211, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

sorry to bother you again, when i was traning, it seems that the download of pretrain of vocos fails, but my network is ok,
how can i fix it?

**Comment by adelacvg** [comment]
You can download and load the model from Hugging Face yourself. Modify the  function `from_pretrained` in the Vocos class to the model's local path. Hope this helps you.

**Comment by yihaoyao402** [comment]
sorry to bother again, i want to know the details of loading local model, 
![JV$(B)90(P9HO3BFXZUZQ95](https://github.com/adelacvg/NS2VC/assets/76078645/6d2831d4-4b69-4e7a-9d18-84abb5df083a)
![~D A_F%J)NMO}PR7F( 3JGJ](https://github.com/adelacvg/NS2VC/assets/76078645/23d3df2e-b136-4c21-9afc-08cadab4d752)
